# Generated by Django 3.2.3 on 2023-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Длина рулона, м.')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Вес рулона, кг')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления рулона')),
                ('deletion_date', models.DateField(blank=True, null=True, verbose_name='Дата удаления рулона')),
            ],
            options={
                'verbose_name': 'Рулон',
                'verbose_name_plural': 'Рулоны',
                'ordering': ['add_date'],
            },
        ),
    ]
